# Generated by Django 3.0.9 on 2020-08-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200807_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
