# Generated by Django 3.0.9 on 2020-08-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0006_auto_20200807_2053'),
        ('users', '0003_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionRecord',
        ),
    ]
