# Generated by Django 3.0.9 on 2020-08-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_auto_20200806_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('request', 'Request'), ('reply', 'Reply')], max_length=7),
        ),
    ]
