# Generated by Django 3.0.9 on 2020-08-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0003_auto_20200807_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
