# Generated by Django 3.0.9 on 2020-08-09 02:35

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0006_auto_20200807_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed_denied_datetime',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'denied', 'confirmed'}),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=10, no_check_for_status=True),
        ),
    ]
