# Generated by Django 3.0.9 on 2020-08-10 03:48

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0008_auto_20200809_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sent_datetime',
            new_name='date_sent',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='confirmed_denied_datetime',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when={'denied', 'confirmed'}),
        ),
    ]
