# Generated by Django 3.1 on 2020-08-10 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0009_auto_20200809_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
