# Generated by Django 3.1 on 2020-08-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0011_transaction_sent_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sent_by',
            new_name='last_sent_by',
        ),
    ]
