# Generated by Django 3.1 on 2020-08-16 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_planner', '0017_auto_20200815_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='repeat',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='never', max_length=7),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(null=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
