# Generated by Django 3.1 on 2020-08-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0018_auto_20200815_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
