# Generated by Django 3.1 on 2020-08-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0019_auto_20200815_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='datetime_lesson',
            new_name='lesson_datetime',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='repeat',
            field=models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='never', max_length=7),
        ),
    ]
