# Generated by Django 3.1 on 2020-08-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0020_auto_20200815_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='label',
            new_name='name',
        ),
    ]
