# Generated by Django 3.1 on 2020-08-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0021_auto_20200815_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
