# Generated by Django 3.1 on 2020-08-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0023_auto_20200816_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='start_date',
        ),
    ]
