# Generated by Django 3.1 on 2020-08-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_note'),
        ('lesson_planner', '0025_lesson_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='transactions',
        ),
        migrations.AddField(
            model_name='lesson',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='transactions.Transaction'),
        ),
    ]
