# Generated by Django 3.1 on 2020-08-17 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_planner', '0027_auto_20200816_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='confirmed_denied_datetime',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('denied', 'denied')], default='pending', max_length=10, no_check_for_status=True)),
                ('confirmed_denied_datetime', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when={'denied', 'confirmed'})),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
