# Generated by Django 3.1 on 2020-08-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0028_auto_20200816_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_status',
            field=models.ManyToManyField(to='lesson_planner.StudentStatus'),
        ),
    ]
