# Generated by Django 3.1 on 2020-08-17 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0029_lesson_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student_status',
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_planner.lesson'),
        ),
    ]
