# Generated by Django 3.1 on 2020-08-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0030_auto_20200816_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('create', 'Create')], default='create', max_length=7),
        ),
    ]
