# Generated by Django 3.1 on 2020-08-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0033_auto_20200828_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Series',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='session',
            new_name='series',
        ),
    ]
