# Generated by Django 3.1 on 2020-08-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0034_auto_20200828_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='start_date',
        ),
        migrations.AddField(
            model_name='series',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
