# Generated by Django 3.1 on 2020-08-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0035_auto_20200828_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_datetime',
            new_name='datetime',
        ),
    ]
