# Generated by Django 3.1 on 2020-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0036_auto_20200828_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('create', 'Create'), ('denied', 'Denied')], default='create', max_length=7),
        ),
    ]
