# Generated by Django 3.1 on 2020-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0039_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='length',
            field=models.DurationField(null=True),
        ),
    ]
