# Generated by Django 3.1 on 2020-08-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0027_auto_20200816_2057'),
        ('transactions', '0002_transaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_planner.lesson'),
        ),
    ]
