# Generated by Django 3.1 on 2020-08-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200818_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='send_request',
            field=models.CharField(choices=[('send', 'Send'), ('request', 'Request')], default='request', max_length=7),
        ),
    ]
