# Generated by Django 3.1 on 2020-08-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200822_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sent_denied_datetime',
            new_name='received_denied_datetime',
        ),
    ]
