# Generated by Django 3.1 on 2020-08-28 21:46

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20200822_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed_datetime',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when={'n', 'f', 'o', 'c', 'r', 'e', 'm', 'd', 'i'}),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_denied_datetime',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when={'denied', 'received'}),
        ),
    ]
