# Generated by Django 3.1 on 2020-08-28 21:48

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20200828_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sent_datetime',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when={'s', 'n', 'e', 't'}),
        ),
    ]
